version: "2.3.3"

services:
  user-account-postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_account
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - user-account-postgres:/data/postgres
    ports:
      - "5432:5432"

  blog-post-mysql:
    image: mysql:oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: blog_post
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - blog-post-mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  user-account-postgres:
  blog-post-mysql:
